### ISSUE TITLE
Importing Character psy issue

### ISSUE THREAD

**Issue by logoscregor** [soupday/cc_blender_tools#11]
Hi.
Trying to import a character from iclone 7.92 into blender 2.93; and encounter error message: included.
![cc3 error import character message](https://user-images.githubusercontent.com/88612431/128626547-f4b1df47-bb9c-42c6-8f66-09e74fe6a5da.png)
Would love some advice about how to solve this.
Many thanks
Shimon

**Comment by soupday** [comment]
**bpy.ops.import_scene.fbx** is from the **Import-Export: FBX Format** base add-on, check that it's enabled.

**Comment by vfxcentral** [comment]
Same issue. with fbx addon on

**Comment by vfxcentral** [comment]
![image](https://user-images.githubusercontent.com/91705741/135546200-9fc27c3f-bb65-4a83-a86c-1c7cd7ee5206.png)

**Comment by soupday** [comment]
That's a very different error. In fact it's a very puzzling error too...

Are you running some kind of special image / colour space / tone mapping modified version or custom build of Blender perhaps?
Or maybe just a colour space extending or modifying add-on?

The error you show here is Blenders own FBX importer crashing trying to set an image colour space to 'Non-Color', which is a perfectly valid operation, normally.

The colour space options in vanilla Blender are: 'Filmic Log', 'Linear', 'Linear ACES', '**Non-Color**', 'Raw', 'sRGB', 'XYZ'.

Your version of Blender has all sorts of variations on the colour spaces, but since Non-Color isn't one of them, the FBX importer fails.

**Comment by vfxcentral** [comment]
OKay I need to turn off my ocio config most likely. So its not in aces color space

**Comment by vfxcentral** [comment]
![image](https://user-images.githubusercontent.com/91705741/135654412-bf16ee2e-9f5c-4562-8aaf-c8a5e635932b.png)
![image](https://user-images.githubusercontent.com/91705741/135654436-af48bb9d-c877-4bbf-b1ea-cc42adc504d2.png)
SOLVED! Aces messes up FBX imports. TURN OFF ACES by deleting it in your Environment Variable
