### ISSUE TITLE
Materials for imported accessories are not rendering correctly

### ISSUE THREAD

**Issue by cuddlyogre** [soupday/cc_blender_tools#272]
cc_blender_tools 2.1.8
CCIC Blender Pipeline Plugin 2.1.7
CC4 4.42.3004.1
Blender 4.2.0

When I import a character exported from CC4 into Blender using cc blender tools, the normals of the accessory mesh are corrupted. When I import the mesh using the Blender FBX importer, it looks like it should. 

The parts of the mesh with bad normals are almost all triangles. I would love to use all quads, but Marvelous Designer really loves triangles and under most circumstances they perform well enough for my use. But even if the triangles are converted to quads, the corruption remains.

It appears at some point the mesh itself is modified during import because the normals are corrupted even without a material.

First image is in CC4. Second image is in Blender with the bad normals on the left and the good normals on the right. Third is the shading without materials.

![image](https://github.com/user-attachments/assets/16134077-f0ea-4c1a-bb66-36f9942cdc9a)
![image](https://github.com/user-attachments/assets/de845160-a651-4e12-965b-80921a1a597d)
![image](https://github.com/user-attachments/assets/e0b469ed-aa71-4e32-8501-ce7e590d0d4b)

**Comment by soupday** [comment]
The only modification it makes is to set the mesh to smooth shading. Which I had to do because character creator had a habit of exporting some objects with flat shading. It doesn't seem to be a problem now so I think I will stop it doing that.

That sort of normal corruption tends to happen when any _custom split normals_ don't align well with Blender's smooth shading algorithm.

So you could look at the _custom split normals_ in the mesh geometry data. You could try clearing them and rebuilding the normals in Blender with the **Object** -> **Shade Auto Smooth** menu operator.

You can also get character creator to rebuild the normals with the **Mesh menu** -> **Edit Normals** > **Auto-smooth** option.

**Comment by cuddlyogre** [comment]
That did the trick. I didn't even know that was there.

![image](https://github.com/user-attachments/assets/75facdbe-e68e-4ab5-b4e6-009593cc33e5)
